# GAUSSIAN NOISE DEMO

In [178]:
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 13 15:44:37 2022

@author: jeffr
"""

'''
DESCRIPTION: applies chosen augmentation method to supplied dataframe.
It is assumed that that the labels column is located at the END of the dataframe.

INPUTS:
data = dataframe
nrows = number of rows that will be created in augmentation

OPTIONAL:
nvalues = number of values being swapped, limited to column length

PMONE and GAUSNOISE ONLY:
unit = amount being plus or minused
noise = 
'''

'\nDESCRIPTION: applies chosen augmentation method to supplied dataframe.\nIt is assumed that that the labels column is located at the END of the dataframe.\n\nINPUTS:\ndata = dataframe\nnrows = number of rows that will be created in augmentation\n\nOPTIONAL:\nnvalues = number of values being swapped, limited to column length\n\nPMONE and GAUSNOISE ONLY:\nunit = amount being plus or minused\nnoise = \n'

In [180]:
#import libraries
import numpy as np
import pandas as pd
import random
from sklearn.model_selection import train_test_split

# LOAD DATASET

In [183]:
#load dataset
#data = np.loadtxt("uniform_small_d_1.tex")
data = np.loadtxt("uniform_large_d_1.tex")
#data = np.loadtxt("gaussian_small_d_1.tex")
#data = np.loadtxt("gaussian_large_d_1.tex")

# Creating NumPy array
array = np.array(data)

# Converting to Pandas DataFrame
df_table = pd.DataFrame(array)

# Displaying the table
df_table.head()

,0,1,2,3,4,5,6,7,8,9,...,141,142,143,144,145,146,147,148,149,150
0,0.604431,0.724054,1.295053,0.495865,0.607451,0.547615,0.564150,0.468880,0.420394,0.910129,...,0.660629,1.325968,1.282151,0.600550,0.592177,0.776711,1.085891,1.153748,1.352572,1.0
1,1.180423,1.391002,1.184481,0.583052,1.210490,0.923676,1.185203,1.369972,1.201448,0.614857,...,0.892705,0.848612,1.298801,1.250497,0.547771,1.215082,0.940952,1.109552,1.181372,1.0
2,1.067779,0.718696,0.798901,1.369462,0.470935,0.566282,1.398846,1.015372,0.801271,1.330270,...,1.339399,0.417466,0.496915,0.661756,0.875185,1.293924,0.750581,0.742218,0.993983,1.0
3,0.368247,0.730771,0.134119,0.984532,0.397524,0.470181,0.025061,0.648142,0.016333,0.973801,...,0.086188,0.394613,0.252668,0.808593,0.587922,0.827502,0.862651,0.684517,0.149873,0.0
4,0.919760,0.577797,0.441661,0.862139,0.263016,0.393494,0.635624,0.657747,0.781920,0.566910,...,0.816635,0.319880,0.770176,0.919029,0.265299,0.983398,0.956898,0.175083,0.170124,0.0

# SPLIT DATASET

In [186]:
# From the dataset, change 25 columns to 'categorical'
#Loop, converts floats to ints and then those ints to category
for i in range(25):
    df_table.iloc[:,i] = df_table.iloc[:,i].round()
    df_table.iloc[:,i] = df_table.iloc[:,i].astype(int)
    df_table.iloc[:,i] = df_table.iloc[:,i].astype("category")

df_table.iloc[:, 150] = df_table.iloc[:, 150].astype("category")

df_table.head()

,0,1,2,3,4,5,6,7,8,9,...,141,142,143,144,145,146,147,148,149,150
0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,...,0.660629,1.325968,1.282151,0.600550,0.592177,0.776711,1.085891,1.153748,1.352572,1.0
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.892705,0.848612,1.298801,1.250497,0.547771,1.215082,0.940952,1.109552,1.181372,1.0
2,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1.339399,0.417466,0.496915,0.661756,0.875185,1.293924,0.750581,0.742218,0.993983,1.0
3,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.086188,0.394613,0.252668,0.808593,0.587922,0.827502,0.862651,0.684517,0.149873,0.0
4,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,...,0.816635,0.319880,0.770176,0.919029,0.265299,0.983398,0.956898,0.175083,0.170124,0.0

In [188]:
#split dataset into training set and test set
#test_size: in this case it is 70% training and 30% testing
#random_state: sets a seed for a random number generator that splits the data
X_train, X_test, y_train, y_test = train_test_split(df_table.iloc[:,0:150], df_table.iloc[:,-1], test_size=0.2, random_state=52)

# CALL SUPER FUNCTION

In [191]:
def betterApplyAugmentationMethods(X_train, method, nrows, nvalues=None, unit=None, noise=None):
    
    # If nvalues not specified, entire column is selected
    if nvalues == None:
        nvalues = data.shape[1]-1
        
    #FABI CODE
    # Assumes the last column is the label column
    #label_column = data.columns[-1]  # Assumes the last column is the label column
    #FABI CODE STOPS HERE
    
    if str(method).lower() == 'gausnoise':
        # Creates empty dataframe to hold augmented rows
        augmentedDf = pd.DataFrame()
        
        # Selects random rows from data and appends to augmentedDf
        for i in range(nrows):
            augmentedDf = pd.concat([augmentedDf, X_train.iloc[[random.randint(0, X_train.shape[0]-1)]]], ignore_index=True)
        
        # Drops label column of augmentedDf
        #augmentedDf = augmentedDf.drop(augmentedDf.shape[1]-1, axis=1)
        #FABI CODE
        #augmentedDf = augmentedDf.drop(label_column, axis=1) 
        #FABI CODE STOPS HERE
        
        # Selects random unique column index 
        randCols = random.sample(range(0, X_train.shape[1]-1), nvalues)
        
        # Applies Gaussian noise to randCols values stored in array
        for i in range(augmentedDf.shape[0]):
            for cols in randCols:
                augmentedDf.iloc[i, cols] += np.random.normal(0, noise)
            
        
        # Combines both data and augmentedDf for full augmented dataframe
        #augmentedDf = pd.concat([data, augmentedDf], ignore_index=True)
            
        
        return augmentedDf
    
    elif str(method).lower() == 'modgausnoise':
        # Creates an empty dataframe to hold augmented observations
        augmentedDf = pd.DataFrame()
        
        # Randomly selects unique column indexs from data
        randCols = random.sample(range(0, X_train.shape[1]-1), nvalues)
        
        # Appends randomly selected rows from data to augmentedDf
        for i in range(nrows):
            augmentedDf = pd.concat([augmentedDf, X_train.iloc[[random.randint(0, X_train.shape[0]-1)]]], ignore_index=True)
            
        # Drops labels from augmentedDf
        #augmentedDf = augmentedDf.drop(augmentedDf.shape[1]-1, axis=1)
        #FABI CODE
        #augmentedDf = augmentedDf.drop(label_column, axis=1) 
        #FABI CODE STOPS HERE
        
        # Generates Gaussian distribution based on columns summary statistics
        # Swaps value with random value in generated Gaussian distribution
        for col in randCols:
            for i in range(augmentedDf.shape[0]):
                mean = augmentedDf[col].mean()
                stDev = augmentedDf[col].std()
                
                augmentedDf.iloc[i, col] =  np.random.normal(mean, stDev)
                
        return augmentedDf
            
        # Combines both data and augmentedDf into final dataframe
        #FABI CODE
        # Add back label column with NaN values
        #augmentedDf[label_column] = np.nan  
        #FABI CODE STOPS HERE
        #augmentedDf = pd.concat([data, augmentedDf], axis=0, ignore_index=True)

        #return augmentedDf
    
    else:
        print("Method not found")
        return None

In [193]:
# Define parameters for augmentation

nrows = 10  # Number of new rows to be created
nvalues = 4  # Number of columns to apply noise to (adjust as needed)
noise = 0.1  # Standard deviation of Gaussian noise

# Apply the gausnoise method
augmented_df_gausnoise = betterApplyAugmentationMethods(X_train, 'gausnoise', nrows, nvalues, noise=noise)
print("Gausnoise Method:")
print(augmented_df_gausnoise)

# Apply the modgausnoise method
augmented_df_modgausnoise = betterApplyAugmentationMethods(X_train, 'modgausnoise', nrows, nvalues, noise=noise)
print("\nModGausnoise Method:")
print(augmented_df_modgausnoise)

TypeError: Cannot setitem on a Categorical with a new category (1.154424832589534), set the categories first